### ISSUE TITLE
RFC: API of a helper

### ISSUE THREAD

**Issue by DavertMik** [codecept-js/mailslurp-helper#2]
Ok, let's clarify method names and API

```js
// create emails
const email = await I.haveNewMailbox(); // creates a new mailbox, which will be deleted after a 
const email2 = await I.haveMailbox('user@mailslurp.com'); // or use predefined mailbox
const email3 = await I.haveNewMailbox('user2@mailslurp.com'); // creates a new mailbox with predefined name, will be deleted after a test

I.registerUser(email);
I.click('Forgot password'); // trigger some action to send emails

// a mailbox can be set explicitly like this (to use with multiple emails)
I.openMailbox(email, () => {
   I.waitForEmailReceived(20);
   I.seeNumOfEmails(1);
   I.seeInLastEmail()
   I.seeSubjectOfLastEmailEquals()
   I.seeInSubjectOfLastEmail()
   I.seeLastEmailIsTo('User Name ' + email);
   I.clickLinkInEmail();
});

// or implicitly like here, we just use last created mailbox

   I.waitForEmailReceived(20);
   I.seeNumOfEmails(1);
   I.seeInLastEmail()
   I.seeSubjectOfLastEmailEquals()
   I.seeInSubjectOfLastEmail()
   I.seeLastEmailIsTo('User Name ' + email);
   I.clickLinkInEmail();

```

**Comment by jackmahoney** [comment]
Ok. I have:
- regenerated the SDKs to use nice method names
- locked versions for npm mailslurp-client
- updated pricing to include free accounts.

That API looks nice. I'm not familiar with how to implement a plugin though. Would you have bandwidth to do this @DavertMik ?

Here is the [npm library for MailSlurp](https://npmjs.com/package/mailslurp-client).

Here are the [docs for all the methods](https://github.com/mailslurp/mailslurp-client-ts-js/blob/master/docs/classes/_index_.mailslurp.md). 

If you set up a scaffold for the CodeCept part I can add the MailSlurp code.

How does that sound?

**Comment by jackmahoney** [comment]
Some changes:
- currently MailSlurp doesn't allow predefined names, they are randomly assigned for new email addresses instead unless a paid plan is used
- the rest looks good if you set up those methods as stubs for me

**Comment by DavertMik** [comment]
Ok, I added some API improvements. So currently I would like to have it working like this:

```js

I.openMailbox(email, () => {
  I.openEmail({subject: /Forgot password/}, () => {
    I.seeInEmailSubject('Forgot password');
    I.seeInEmailBody('Reset link');
    I.seeEmailHasAttachments();
    I.clickLinkInEmail();
  });
});

```
